Repository punk-link/warp, pull requests merged in 2024-10, with the labels that each got.

#96 Feature/81 merge report and entry api controllers
  Warp.WebApp/Controllers/EntryController.cs
  Warp.WebApp/Controllers/ReportController.cs
  Warp.WebApp/wwwroot/js/entry.js
Labels: enhancement

#97 Visual image upload indication added
  Warp.WebApp/wwwroot/js/modules/image-processor.js
Labels: enhancement

#98 Enhance accessibility and add Fancybox for image viewing
  Warp.WebApp/Pages/Entry.cshtml
  Warp.WebApp/Pages/Preview.cshtml
  Warp.WebApp/Pages/Shared/Components/ReadOnlyImageContainer.cshtml
  Warp.WebApp/Pages/Shared/_Head.cshtml
  Warp.WebApp/wwwroot/js/entry.js
  Warp.WebApp/wwwroot/js/preview.js
Labels: enhancement, refactoring

#99 Feature/80 add global exception handler middleware
  Warp.Measurements/Warp.Measurements.csproj
  Warp.WebApp.Tests/Warp.WebApp.Tests.csproj
  Warp.WebApp/Controllers/EntryController.cs
  Warp.WebApp/Extensions/Logging/LogMessages.cs
  Warp.WebApp/Middlewares/ApiExceptionHandlerMiddleware.cs
  Warp.WebApp/Program.cs
  Warp.WebApp/Warp.WebApp.csproj
Labels: enhancement

#100 Bugfix/92 preview page scripts crashes on dev
  Warp.WebApp/Controllers/EntryController.cs
  Warp.WebApp/Warp.WebApp.csproj
  Warp.WebApp/wwwroot/js/preview.js
Labels: bug

#102 Refactored and cleaned up SCSS files.
  Warp.WebApp/Data/Redis/KeydbStorage.cs
  Warp.WebApp/Styles/components/_buttons.scss
  Warp.WebApp/Styles/components/_forms.scss
  Warp.WebApp/Styles/components/_image-processors.scss
  Warp.WebApp/Styles/components/_modals.scss
  Warp.WebApp/Styles/components/_navs.scss
  Warp.WebApp/Styles/layout/_typography.scss
  Warp.WebApp/Styles/main.scss
  Warp.WebApp/Styles/utils/_animations.scss
  Warp.WebApp/Styles/utils/_functions.scss
  Warp.WebApp/Styles/variables/_colors.scss
  Warp.WebApp/Styles/variables/_fonts.scss
  Warp.WebApp/Styles/variables/_sizing.scss
  Warp.WebApp/Styles/variables/_variables.scss
  Warp.WebApp/wwwroot/css/main.min.css
  Warp.WebApp/wwwroot/css/main.min.css.map
  Warp.WebApp/wwwroot/js/index.js
Labels: refactoring

#103 Feature/68 unify log messages add traces
  Warp.WebApp/Attributes/TraceMethodAttribute.cs
  Warp.WebApp/Constants/Logging/LoggingConstants.cs
  Warp.WebApp/Data/DataStorage.cs
  Warp.WebApp/Helpers/Configuration/DistributedCacheHelper.cs
  Warp.WebApp/Helpers/Configuration/VaultHelper.cs
  Warp.WebApp/Helpers/Warmups/WarmupService.cs
  Warp.WebApp/Middlewares/ApiExceptionHandlerMiddleware.cs
  Warp.WebApp/Middlewares/CancellationExceptionHandlerMiddleware.cs
  Warp.WebApp/Middlewares/RobotsMiddleware.cs
  Warp.WebApp/Middlewares/TraceMethodMiddleware.cs
  Warp.WebApp/Pages/BasePageModel.cs
  Warp.WebApp/Program.cs
  Warp.WebApp/Services/Creators/CreatorService.cs
  Warp.WebApp/Services/Entries/EntryService.cs
  Warp.WebApp/Services/Entries/ReportService.cs
  Warp.WebApp/Services/Entries/ViewCountService.cs
  Warp.WebApp/Services/Images/ImageService.cs
  Warp.WebApp/Services/Infrastructure/PartialViewRenderService.cs
  Warp.WebApp/Services/Infrastructure/UrlService.cs
  Warp.WebApp/Services/TextFormatter.cs
  Warp.WebApp/Telemetry/Logging/LogMessages.cs
  Warp.WebApp/Telemetry/Logging/LoggingExtensions.cs
  Warp.WebApp/Telemetry/Metrics/ApplicationMetrics.cs
  Warp.WebApp/Telemetry/Metrics/MetricsExtensions.cs
  Warp.WebApp/Telemetry/TelemetryExtensions.cs
  Warp.WebApp/Telemetry/Tracing/TelemetryExtensions.cs
  Warp.WebApp/Warp.WebApp.csproj
Labels: enhancement

#104 Refactor EntryService.Get method for modularity.
  Warp.WebApp/Services/Entries/EntryService.cs
Labels: refactoring

#106 Feature/86 add mode initialization on page start
  Warp.WebApp/Controllers/ImageController.cs
  Warp.WebApp/Pages/Index.cshtml
  Warp.WebApp/Pages/Index.cshtml.cs
  Warp.WebApp/Pages/Shared/Components/EditableImageContainer.cshtml
  Warp.WebApp/Pages/Shared/Components/EditableImageContainer.cshtml.cs
  Warp.WebApp/Services/Images/ImageService.cs
  Warp.WebApp/wwwroot/js/components/textarea.js
  Warp.WebApp/wwwroot/js/index.js
Labels: bug, enhancement

#101 S3 impl
  Warp.WebApp.Tests/OpenGraphServiceTests.cs
  Warp.WebApp/Controllers/ImageController.cs
  Warp.WebApp/Data/S3/AmazonS3Factory.cs
  Warp.WebApp/Data/S3/IAmazonS3Factory.cs
  Warp.WebApp/Data/S3/IS3FileStorage.cs
  Warp.WebApp/Data/S3/S3FileStorage.cs
  Warp.WebApp/Data/S3/S3Options.cs
  Warp.WebApp/Models/Entry.cs
  Warp.WebApp/Models/EntryInfo.cs
  Warp.WebApp/Pages/Entry.cshtml.cs
  Warp.WebApp/Pages/Index.cshtml.cs
  Warp.WebApp/Pages/Preview.cshtml.cs
  Warp.WebApp/Program.cs
  Warp.WebApp/Services/Entries/EntryService.cs
  Warp.WebApp/Services/IdCoder.cs
  Warp.WebApp/Services/Images/IImageService.cs
  Warp.WebApp/Services/Images/ImageService.cs
  Warp.WebApp/Services/OpenGraphService.cs
  Warp.WebApp/Warp.WebApp.csproj
  Warp.WebApp/wwwroot/js/components/textarea.js
Labels: enhancement

#112 Refactoring/entry info rearrangement
  Warp.WebApp/Constants/Logging/LoggingConstants.cs
  Warp.WebApp/Controllers/BaseController.cs
  Warp.WebApp/Controllers/EntryController.cs
  Warp.WebApp/Controllers/ImageController.cs
  Warp.WebApp/Data/DataStorage.cs
  Warp.WebApp/Data/S3/AmazonS3Factory.cs
  Warp.WebApp/Data/S3/IS3FileStorage.cs
  Warp.WebApp/Data/S3/S3FileStorage.cs
  Warp.WebApp/Helpers/ProblemDetailsHelper.cs
  Warp.WebApp/Models/Creators/Creator.cs
  Warp.WebApp/Models/Entry.cs
  Warp.WebApp/Models/EntryInfo.cs
  Warp.WebApp/Models/Validators/EntryInfoValidator.cs
  Warp.WebApp/Models/Validators/EntryValidator.cs
  Warp.WebApp/Pages/BasePageModel.cs
  Warp.WebApp/Pages/Entry.cshtml.cs
  Warp.WebApp/Pages/Error.cshtml.cs
  Warp.WebApp/Pages/Index.cshtml.cs
  Warp.WebApp/Pages/Preview.cshtml.cs
  Warp.WebApp/Program.cs
  Warp.WebApp/Resources/ServerResources.en-US.resx
  Warp.WebApp/Resources/ServerResources.resx
  Warp.WebApp/Services/CacheKeyBuilder.cs
  Warp.WebApp/Services/Creators/CookieService.cs
  Warp.WebApp/Services/Creators/CreatorService.cs
  Warp.WebApp/Services/Creators/ICookieService.cs
  Warp.WebApp/Services/Creators/ICreatorService.cs
  Warp.WebApp/Services/Entries/EntryPresentationService.cs
  Warp.WebApp/Services/Entries/EntryService.cs
  Warp.WebApp/Services/Entries/IEntryPresentationService.cs
  Warp.WebApp/Services/Entries/IEntryService.cs
  Warp.WebApp/Services/EntryInfoService.cs
  Warp.WebApp/Services/IEntryInfoService.cs
  Warp.WebApp/Services/Images/IImageService.cs
  Warp.WebApp/Services/Images/ImageService.cs
  Warp.WebApp/Services/OpenGraph/IOpenGraphService.cs
  Warp.WebApp/Services/OpenGraph/OpenGraphService.cs
  Warp.WebApp/Telemetry/Logging/LogMessages.cs
Labels: refactoring
